<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sitemenu/_edit.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 3:53:13 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit SiteMenu')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sitemenus.index')}}">Manage</a>
<form action="{{route('sitemenus.update',$sitemenu)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$sitemenu->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="link" class="col-sm-2 col-form-label">Link</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="link" value="{{$sitemenu->link}}" id="link" placeholder="Link">
	</div>
</div>
<div class="row mb-3">
	<label for="has_child" class="col-sm-2 col-form-label">Has Child</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="has_child" value="{{$sitemenu->has_child}}"  id="has_child" placeholder="Has Child">
	</div>
</div>
<div class="row mb-3">
	<label for="inactive" class="col-sm-2 col-form-label">Inactive</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="inactive" value="{{$sitemenu->inactive}}"   id="inactive" placeholder="Inactive">
	</div>
</div>
<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
