<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sitemenu/_show.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 3:53:13 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show SiteMenu')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sitemenus.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$sitemenu->id}}</td></tr>
		<tr><th>Name</th><td>{{$sitemenu->name}}</td></tr>
		<tr><th>Link</th><td>{{$sitemenu->link}}</td></tr>
		<tr><th>Has Child</th><td>{{$sitemenu->has_child}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
