<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/order/_index.blade.php" was generated by ProBot AI.
* Date: 5/2/2023 4:14:56 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Order')
@section('style')


@endsection
@section('page')


<div class="container p-3">
<div class=""><a href="{{route('orders.create')}}" class="btn btn-primary">New Order</a></div>
<table class="table table-hover text-nowrap table-bordered">
	<thead>
		<tr>
			<th>Id</th>
			<th>Customer</th>
			<th>Order Date</th>
			<th>Order Total</th>
			<th>Paid Amount</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($orders as $order)
		<tr>
			<td>{{$order->id}}</td>
			<td>{{$order->c_name}}</td>
			<td>{{$order->order_date}}</td>
			<td>{{$order->order_total}}</td>
			<td>{{$order->paid_amount}}</td>
			<td>{{$order->created_at}}</td>
			<td>{{$order->updated_at}}</td>

			<td>
			<form action = "{{route('orders.destroy',$order->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('orders.show',$order->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('orders.edit',$order->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
</div>
@endsection
@section('script')


@endsection
