<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/siteproduct/_create.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 2:53:13 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create SiteProduct')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('siteproducts.index')}}">Manage</a>
<form action="{{route('siteproducts.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="site_product_category_id" class="col-sm-2 col-form-label">Site_Product_Category</label>
	<div class="col-sm-10">
		<select class="form-control" name="site_product_category_id" id="site_product_category_id">
			@foreach($site_product_categorys as $site_product_category)
				<option value="{{$site_product_category->id}}">{{$site_product_category->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="description" id="description" placeholder="Description"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo" id="photo" placeholder="Photo">
	</div>
</div>
<div class="row mb-3">
	<label for="regular_price" class="col-sm-2 col-form-label">Regular Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="regular_price" id="regular_price" placeholder="Regular Price">
	</div>
</div>
<div class="row mb-3">
	<label for="offer_price" class="col-sm-2 col-form-label">Offer Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="offer_price" id="offer_price" placeholder="Offer Price">
	</div>
</div>
<div class="row mb-3">
	<label for="current_stock" class="col-sm-2 col-form-label">Current Stock</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="current_stock" id="current_stock" placeholder="Current Stock">
	</div>
</div>
<div class="row mb-3">
	<label for="site_product_uom_id" class="col-sm-2 col-form-label">Site_Product_Uom</label>
	<div class="col-sm-10">
		<select class="form-control" name="site_product_uom_id" id="site_product_uom_id">
			@foreach($site_product_uoms as $site_product_uom)
				<option value="{{$site_product_uom->id}}">{{$site_product_uom->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="slug" class="col-sm-2 col-form-label">Slug</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="slug" id="slug" placeholder="Slug">
	</div>
</div>
<div class="row mb-3">
	<label for="icon" class="col-sm-2 col-form-label">Icon</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="icon" id="icon" placeholder="Icon">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
