<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/siteproduct/_edit.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 2:53:13 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit SiteProduct')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('siteproducts.index')}}">Manage</a>
<form action="{{route('siteproducts.update',$siteproduct)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$siteproduct->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="site_product_category_id" class="col-sm-2 col-form-label">Site_Product_Category</label>
	<div class="col-sm-10">
		<select class="form-control" name="site_product_category_id" id="site_product_category_id">
			@foreach($site_product_categorys as $site_product_category)
				@if($site_product_category->id==$siteproduct->site_product_category_id)
					<option value="{{$site_product_category->id}}" selected>{{$site_product_category->name}}</option>
				@else
					<option value="{{$site_product_category->id}}">{{$site_product_category->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="description" value="{{$siteproduct->description}}" id="description" placeholder="Description">
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo"  id="photo" placeholder="Photo">
	</div>
</div>
<div class="row mb-3">
	<label for="regular_price" class="col-sm-2 col-form-label">Regular Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="regular_price" value="{{$siteproduct->regular_price}}" id="regular_price" placeholder="Regular Price">
	</div>
</div>
<div class="row mb-3">
	<label for="offer_price" class="col-sm-2 col-form-label">Offer Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="offer_price" value="{{$siteproduct->offer_price}}" id="offer_price" placeholder="Offer Price">
	</div>
</div>
<div class="row mb-3">
	<label for="current_stock" class="col-sm-2 col-form-label">Current Stock</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="current_stock" value="{{$siteproduct->current_stock}}" id="current_stock" placeholder="Current Stock">
	</div>
</div>
<div class="row mb-3">
	<label for="site_product_uom_id" class="col-sm-2 col-form-label">Site_Product_Uom</label>
	<div class="col-sm-10">
		<select class="form-control" name="site_product_uom_id" id="site_product_uom_id">
			@foreach($site_product_uoms as $site_product_uom)
				@if($site_product_uom->id==$siteproduct->site_product_uom_id)
					<option value="{{$site_product_uom->id}}" selected>{{$site_product_uom->name}}</option>
				@else
					<option value="{{$site_product_uom->id}}">{{$site_product_uom->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="slug" class="col-sm-2 col-form-label">Slug</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="slug" value="{{$siteproduct->slug}}" id="slug" placeholder="Slug">
	</div>
</div>
<div class="row mb-3">
	<label for="icon" class="col-sm-2 col-form-label">Icon</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="icon" value="{{$siteproduct->icon}}" id="icon" placeholder="Icon">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
