<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/siteproduct/_index.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 2:53:13 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage SiteProduct')
@section('style')


@endsection
@section('page')
<a href="{{route('siteproducts.create')}}">New SiteProduct</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Site Product Category Id</th>
			<th>Description</th>
			<th>Photo</th>
			<th>Regular Price</th>
			<th>Offer Price</th>
			<th>Inactive</th>
			<th>Current Stock</th>
			<th>Site Product Uom Id</th>
			<th>Slug</th>
			<th>Icon</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($siteproducts as $siteproduct)
		<tr>
			<td>{{$siteproduct->id}}</td>
			<td>{{$siteproduct->name}}</td>
			<td>{{$siteproduct->site_product_category_id}}</td>
			<td>{{$siteproduct->description}}</td>
			<td><img src="{{asset('img/'.$siteproduct->photo)}}" width="100" /></td>
			<td>{{$siteproduct->regular_price}}</td>
			<td>{{$siteproduct->offer_price}}</td>
			<td>{{$siteproduct->inactive}}</td>
			<td>{{$siteproduct->current_stock}}</td>
			<td>{{$siteproduct->site_product_uom_id}}</td>
			<td>{{$siteproduct->slug}}</td>
			<td>{{$siteproduct->icon}}</td>

			<td>
			<form action = "{{route('siteproducts.destroy',$siteproduct->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('siteproducts.show',$siteproduct->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('siteproducts.edit',$siteproduct->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
