<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/siteproduct/_show.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 2:53:13 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show SiteProduct')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('siteproducts.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$siteproduct->id}}</td></tr>
		<tr><th>Name</th><td>{{$siteproduct->name}}</td></tr>
		<tr><th>Site Product Category Id</th><td>{{$siteproduct->site_product_category_id}}</td></tr>
		<tr><th>Description</th><td>{{$siteproduct->description}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$siteproduct->photo)}}" width="100" /></td></tr>
		<tr><th>Regular Price</th><td>{{$siteproduct->regular_price}}</td></tr>
		<tr><th>Offer Price</th><td>{{$siteproduct->offer_price}}</td></tr>
		<tr><th>Inactive</th><td>{{$siteproduct->inactive}}</td></tr>
		<tr><th>Current Stock</th><td>{{$siteproduct->current_stock}}</td></tr>
		<tr><th>Site Product Uom Id</th><td>{{$siteproduct->site_product_uom_id}}</td></tr>
		<tr><th>Slug</th><td>{{$siteproduct->slug}}</td></tr>
		<tr><th>Icon</th><td>{{$siteproduct->icon}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
