<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_index.blade.php" was generated by ProBot AI.
* Date: 5/4/2023 9:13:42 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Product')
@section('style')


@endsection

@section('page')

<div class="content-header">
	<div class="container-fluid">

		<div class="content">
			<div class="container-fluid">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Manage Product</h3>

						<div class="card-tools">
							@if(session()->has('message'))
							<div class="alert alert-success">
								{{ session()->get('message') }}
							</div>
							@endif
							<div class="input-group input-group-sm">
								<input type="text" name="table_search" id="search" class="form-control float-right" placeholder="Search" onkeyup="search()">

								<div class="input-group-append">
									<button type="submit" class="btn btn-default" onkeyup="search()">
										<i class="fas fa-search"></i>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="card-body table-responsive p-0">
						<a href="{{route('products.create')}}" class="btn btn-primary  m-2 p-2">New Product</a>
						<table class="table table-hover text-nowrap" name='table' id='table'>
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Offer Price</th>
									<th>Regular Price</th>
									<th>Description</th>
									<th>Photo</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach($products as $product)
								<tr>
									<td>{{$product->id}}</td>
									<td>{{$product->name}}</td>
									<td>{{$product->offer_price}}</td>
									<td>{{$product->regular_price}}</td>
									<td>{{$product->description}}</td>
									<td style="padding:0px"><img src="{{asset('img/'.$product->photo)}}" width="70px" /></td>



									<td>
										<form action="{{route('products.destroy',$product->id)}}" method="post">
											<a class='btn btn-primary' href="{{route('products.show',$product->id)}}">View</a>
											<a class='btn btn-success' href="{{route('products.edit',$product->id)}}"> Edit </a>
											@method('DELETE')
											@csrf
											<input type="submit" class="btn btn-danger" name="delete" value="Delete" />
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
							
						</table>
						{{ $products->links() }}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection
@section('script')
<script>
	function search() {



		var search = document.getElementById('search').value

		var table = document.getElementById('table')


		var tr = table.getElementsByTagName('tr')


		for (i = 0; i < tr.length; i++) {

			var td = tr[i].getElementsByTagName('td')



			for (j = 0; j < td.length; j++) {
				var content = td[j].textContent

				if (content.indexOf(search) > -1) {
					tr[i].style.display = "";
					// tr[i].style.color = "green"

					break;


				} else {
					tr[i].style.display = "none";

				}

			}

		}



	}
</script>

@endsection