<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sitesection/_index.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 3:09:28 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage SiteSection')
@section('style')


@endsection
@section('page')
<div class="content-header">
	<div class="container-fluid">
		<div class="content">
			<div class="container-fluid">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Manage Product</h3>

						<div class="card-tools">
							@if(session()->has('message'))
							<div class="alert alert-success">
								{{ session()->get('message') }}
							</div>
							@endif
							<div class="input-group input-group-sm">
								<input type="text" name="table_search" id="search" class="form-control float-right" placeholder="Search" onkeyup="search()">

								<div class="input-group-append">
									<button type="submit" class="btn btn-default" onkeyup="search()">
										<i class="fas fa-search"></i>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="card-body table-responsive p-0">
<a href="{{route('sitesections.create')}}" class="btn btn-primary m-2 p-2">New SiteSection</a>
<table class="table table-hover text-nowrap " id="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($sitesections as $sitesection)
		<tr>
			<td>{{$sitesection->id}}</td>
			<td>{{$sitesection->name}}</td>
			<td>{{$sitesection->inactive}}</td>

			<td>
			<form action = "{{route('sitesections.destroy',$sitesection->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('sitesections.show',$sitesection->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('sitesections.edit',$sitesection->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
