<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sitesection/_show.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 3:09:28 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show SiteSection')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sitesections.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$sitesection->id}}</td></tr>
		<tr><th>Name</th><td>{{$sitesection->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
