<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/productcategory/_edit.blade.php" was generated by ProBot AI.
* Date: 5/4/2023 9:58:37 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit ProductCategory')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('productcategories.index')}}">Manage</a>
<form action="{{route('productcategories.update',$productcategory)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$productcategory->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="section_id" class="col-sm-2 col-form-label">Section</label>
	<div class="col-sm-10">
		<select class="form-control" name="section_id" id="section_id">
			@foreach($sections as $section)
				@if($section->id==$productcategory->site_section_id)
					<option value="{{$section->id}}" selected>{{$section->name}}</option>
				@else
					<option value="{{$section->id}}">{{$section->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="has_child" class="col-sm-2 col-form-label">Has Child</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="has_child" value="{{$productcategory->has_child}}" id="name" placeholder="Name">
	</div>
</div>
<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
