<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/warehouse/_create.blade.php" was generated by ProBot AI.
* Date: 5/6/2023 11:30:14 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Warehouse')
@section('style')


@endsection
@section('page')
<div class="container m-2">
<a class="btn btn-primary pl-5 pr-5" href="{{route('warehouses.index')}}">Manage</a>
<form action="{{route('warehouses.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="city" class="col-sm-2 col-form-label">City</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="city" id="city" placeholder="City">
	</div>
</div>
<div class="row mb-3">
	<label for="contact" class="col-sm-2 col-form-label">Contact</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="contact" id="contact" placeholder="Contact">
	</div>
</div>

<button type="submit"class="btn btn-primary pl-5 pr-5">Save</button>
</form>

<div>
@endsection
@section('script')


@endsection
