<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/warehouse/_edit.blade.php" was generated by ProBot AI.
* Date: 5/6/2023 11:30:14 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Warehouse')
@section('style')


@endsection
@section('page')
<div class='container'>
<a class='btn btn-primary p-2 m-2'  href="{{route('warehouses.index')}}">Manage</a>
<form action="{{route('warehouses.update',$warehouse)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$warehouse->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="city" class="col-sm-2 col-form-label">City</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="city" value="{{$warehouse->city}}" id="city" placeholder="City">
	</div>
</div>
<div class="row mb-3">
	<label for="contact" class="col-sm-2 col-form-label">Contact</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="contact" value="{{$warehouse->contact}}" id="contact" placeholder="Contact">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
