<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/warehouse/_show.blade.php" was generated by ProBot AI.
* Date: 5/6/2023 11:30:14 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Warehouse')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('warehouses.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$warehouse->id}}</td></tr>
		<tr><th>Name</th><td>{{$warehouse->name}}</td></tr>
		<tr><th>City</th><td>{{$warehouse->city}}</td></tr>
		<tr><th>Contact</th><td>{{$warehouse->contact}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
