<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_show.blade.php" was generated by ProBot AI.
* Date: 4/4/2023 3:10:19 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show User')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('users.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$user->id}}</td></tr>
		<tr><th>Username</th><td>{{$user->username}}</td></tr>
		<tr><th>Role Id</th><td>{{$user->role_id}}</td></tr>
		<tr><th>Password</th><td>{{$user->password}}</td></tr>
		<tr><th>Email</th><td>{{$user->email}}</td></tr>
		<tr><th>Full Name</th><td>{{$user->full_name}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$user->photo)}}" width="100" /></td></tr>
		<tr><th>Verify Code</th><td>{{$user->verify_code}}</td></tr>
		<tr><th>Inactive</th><td>{{$user->inactive}}</td></tr>
		<tr><th>Mobile</th><td>{{$user->mobile}}</td></tr>
		<tr><th>Updated At</th><td>{{$user->updated_at}}</td></tr>
		<tr><th>Created At</th><td>{{$user->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
