<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customer/_index.blade.php" was generated by ProBot AI.
* Date: 5/4/2023 9:39:09 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Customer')
@section('style')


@endsection
@section('page')
<div class="content-header">
	<div class="container-fluid">
		<div class="content">
			<div class="container-fluid">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Manage Product</h3>

						<div class="card-tools">
							@if(session()->has('message'))
							<div class="alert alert-success">
								{{ session()->get('message') }}
							</div>
							@endif
							<div class="input-group input-group-sm">
								<input type="text" name="table_search" id="search" class="form-control float-right" placeholder="Search" onkeyup="search()">

								<div class="input-group-append">
									<button type="submit" class="btn btn-default" onkeyup="search()">
										<i class="fas fa-search"></i>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="card-body table-responsive p-0">
						<a href="{{route('customers.create')}}" class="btn btn-primary m-2 p-2">New Customer</a>
						<table class="table table-hover text-nowrap" id='table'>
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Mobile</th>
									<th>Email</th>
									<th>City</th>
									<th>Postcode</th>
									<th>Apartment</th>

									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach($customers as $customer)
								<tr>
									<td>{{$customer->id}}</td>
									<td>{{$customer->name}}</td>
									<td>{{$customer->mobile}}</td>
									<td>{{$customer->email}}</td>
									<td>{{$customer->city}}</td>
									<td>{{$customer->postcode}}</td>
									<td>{{$customer->apartment}}</td>

									<td>
										<form action="{{route('customers.destroy',$customer->id)}}" method="post">
											<a class='btn btn-primary' href="{{route('customers.show',$customer->id)}}">View</a>
											<a class='btn btn-success' href="{{route('customers.edit',$customer->id)}}"> Edit </a>
											@method('DELETE')
											@csrf
											<input type="submit" class="btn btn-danger" name="delete" value="Delete" />
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection
@section('script')
<script>
	function search() {



		var search = document.getElementById('search').value.toLowerCase()

		var table = document.getElementById('table')


		var tr = table.getElementsByTagName('tr')


		for (i = 0; i < tr.length; i++) {

			var td = tr[i].getElementsByTagName('td')



			for (j = 0; j < td.length; j++) {
				var content = td[j].textContent.toLowerCase()

				if (content.indexOf(search) > -1) {
					tr[i].style.display = "";
					// tr[i].style.color = "green"

					break;


				} else {
					tr[i].style.display = "none";

				}

			}

		}



	}
</script>

@endsection