<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customer/_show.blade.php" was generated by ProBot AI.
* Date: 5/4/2023 9:39:09 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Customer')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('customers.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		 <tr><th>Id</th><td>{{$customer->id}}</td></tr>
		<tr><th>Name</th><td>{{$customer->name}}</td></tr>
		<tr><th>Mobile</th><td>{{$customer->mobile}}</td></tr>
		<tr><th>Email</th><td>{{$customer->email}}</td></tr>
		<tr><th>Created At</th><td>{{$customer->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$customer->updated_at}}</td></tr>
		<tr><th>Password</th><td>{{$customer->password}}</td></tr>
		<tr><th>Country Id</th><td>{{$customer->country_id}}</td></tr>
		<tr><th>Street Address</th><td>{{$customer->street_address}}</td></tr>
		<tr><th>City</th><td>{{$customer->city}}</td></tr>
		<tr><th>Postcode</th><td>{{$customer->postcode}}</td></tr>
		<tr><th>Apartment</th><td>{{$customer->apartment}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
