<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sitealbum/_show.blade.php" was generated by ProBot AI.
* Date: 5/8/2023 3:29:35 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show SiteAlbum')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sitealbums.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$sitealbum->id}}</td></tr>
		<tr><th>Name</th><td>{{$sitealbum->name}}</td></tr>
		<tr><th>Created At</th><td>{{$sitealbum->created_at}}</td></tr>
		<tr><th>Description</th><td>{{$sitealbum->description}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$sitealbum->photo)}}" width="100" /></td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
