<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProductController.php" was generated by ProBot AI.
* Date: 5/4/2023 9:11:24 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Manufacturer;
use App\Models\ProductCategory;
use App\Models\siteSection;
use App\Models\Uom;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller{
	public function index(){
		$products = Product::Paginate(10);
		return view("pages.erp.product.index",["products"=>$products]);
	}
	public function create(){
		return view("pages.erp.product.create",["manufacturers"=>Manufacturer::all(),"categories"=>ProductCategory::all(),"sections"=>SiteSection::all(),"uom"=>Uom::all()]);
	}
	public function store(Request $request){
		//Product::create($request->all());
		$product = new Product;
		$product->name=$request->name;
		$product->offer_price=$request->offer_price;
		$product->manufacturer_id=$request->manufacturer_id;
		$product->regular_price=$request->regular_price;
		$product->description=$request->description;
		if(isset($request->photo)){
			$product->photo=$request->photo;
		}
		$product->category_id=$request->category_id;
		$product->site_section_id=$request->site_section_id;
		$product->is_featured=$request->is_featured;
		$product->star=$request->star;
		$product->is_brand=$request->is_brand;
		$product->offer_discount=$request->offer_discount;
		$product->uom_id=$request->uom_id;
		$product->weight=$request->weight;
		$product->barcode=$request->barcode;
date_default_timezone_set("Asia/Dhaka");
		$product->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$product->updated_at=date('Y-m-d H:i:s');

		$product->save();
		if(isset($request->photo)){
			$imageName=$product->id.'.'.$request->photo->extension();
			$product->photo=$imageName;
			$product->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$product = Product::find($id);
		return view("pages.erp.product.show",["product"=>$product]);
	}
	public function edit(Product $product){
		return view("pages.erp.product.edit",["product"=>$product,"manufacturers"=>Manufacturer::all(),"categories"=>ProductCategory::all(),"sections"=>SiteSection::all(),"uom"=>Uom::all()]);
	}
	public function update(Request $request,Product $product){
		//Product::update($request->all());
		$product = Product::find($product->id);
		$product->name=$request->name;
		$product->offer_price=$request->offer_price;
		$product->manufacturer_id=$request->manufacturer_id;
		$product->regular_price=$request->regular_price;
		$product->description=$request->description;
		if(isset($request->photo)){
			$product->photo=$request->photo;
		}
		$product->category_id=$request->category_id;
		$product->site_section_id=$request->site_section_id;
		$product->is_featured=$request->is_featured;
		$product->star=$request->star;
		$product->is_brand=$request->is_brand;
		$product->offer_discount=$request->offer_discount;
		$product->uom_id=$request->uom_id;
		$product->weight=$request->weight;
		$product->barcode=$request->barcode;
date_default_timezone_set("Asia/Dhaka");
		$product->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$product->updated_at=date('Y-m-d H:i:s');

		$product->save();
		if(isset($request->photo)){
			$imageName=$product->id.'.'.$request->photo->extension();
			$product->photo=$imageName;
			$product->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("products.index")->with('success','Updated Successfully.');
	}
	public function destroy(Product $product){
		$product->delete();
		return redirect()->route("products.index")->with('success', 'Deleted Successfully.');
	}

	public function get_product_json(){
        $id=$_GET["id"];     
        $request=Product::find($id);
        return json_encode($request);
    }
}
?>
