<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SectionController.php" was generated by ProBot AI.
* Date: 4/24/2023 1:29:47 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Section;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SectionController extends Controller{
	public function index(){
		$sections = Section::paginate(10);
		return view("pages.erp.section.index",["sections"=>$sections]);
	}
	public function create(){
		return view("pages.erp.section.create",[]);
	}
	public function store(Request $request){
		//Section::create($request->all());
		$section = new Section;
		$section->name=$request->name;

		$section->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$section = Section::find($id);
		return view("pages.erp.section.show",["section"=>$section]);
	}
	public function edit(Section $section){
		return view("pages.erp.section.edit",["section"=>$section,]);
	}
	public function update(Request $request,Section $section){
		//Section::update($request->all());
		$section = Section::find($section->id);
		$section->name=$request->name;

		$section->save();

		return redirect()->route("sections.index")->with('success','Updated Successfully.');
	}
	public function destroy(Section $section){
		$section->delete();
		return redirect()->route("sections.index")->with('success', 'Deleted Successfully.');
	}
}
?>
