<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SiteAlbumController.php" was generated by ProBot AI.
* Date: 5/8/2023 3:29:17 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\SiteAlbum;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SiteAlbumController extends Controller{
	public function index(){
		$sitealbums = SiteAlbum::paginate(10);
		return view("pages.erp.sitealbum.index",["sitealbums"=>$sitealbums]);
	}
	public function create(){
		return view("pages.erp.sitealbum.create",[]);
	}
	public function store(Request $request){
		//SiteAlbum::create($request->all());
		$sitealbum = new SiteAlbum;
		$sitealbum->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$sitealbum->created_at=date('Y-m-d H:i:s');
		$sitealbum->description=$request->description;
		if(isset($request->photo)){
			$sitealbum->photo=$request->photo;
		}

		$sitealbum->save();
		if(isset($request->photo)){
			$imageName=$sitealbum->id.'.'.$request->photo->extension();
			$sitealbum->photo=$imageName;
			$sitealbum->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$sitealbum = SiteAlbum::find($id);
		return view("pages.erp.sitealbum.show",["sitealbum"=>$sitealbum]);
	}
	public function edit(SiteAlbum $sitealbum){
		return view("pages.erp.sitealbum.edit",["sitealbum"=>$sitealbum,]);
	}
	public function update(Request $request,SiteAlbum $sitealbum){
		//SiteAlbum::update($request->all());
		$sitealbum = SiteAlbum::find($sitealbum->id);
		$sitealbum->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$sitealbum->created_at=date('Y-m-d H:i:s');
		$sitealbum->description=$request->description;
		if(isset($request->photo)){
			$sitealbum->photo=$request->photo;
		}

		$sitealbum->save();
		if(isset($request->photo)){
			$imageName=$sitealbum->id.'.'.$request->photo->extension();
			$sitealbum->photo=$imageName;
			$sitealbum->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("sitealbums.index")->with('success','Updated Successfully.');
	}
	public function destroy(SiteAlbum $sitealbum){
		$sitealbum->delete();
		return redirect()->route("sitealbums.index")->with('success', 'Deleted Successfully.');
	}
}
?>
