<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SiteRouteController.php" was generated by ProBot AI.
* Date: 5/12/2023 12:48:40 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\SiteRoute;
use App\Models\SiteMenu;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SiteRouteController extends Controller{
	public function index(){
		$siteroutes = SiteRoute::paginate(10);
		return view("pages.erp.siteroute.index",["siteroutes"=>$siteroutes]);
	}
	public function create(){
		return view("pages.erp.siteroute.create",["sitemenus"=>SiteMenu::all()]);
	}
	public function store(Request $request){
		//SiteRoute::create($request->all());
		$siteroute = new SiteRoute;
		$siteroute->name=$request->name;
		$siteroute->src=$request->src;
		$siteroute->inactive=$request->inactive;
		$siteroute->site_menu_id=$request->site_menu_id;

		$siteroute->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$siteroute = SiteRoute::find($id);
		return view("pages.erp.siteroute.show",["siteroute"=>$siteroute]);
	}
	public function edit(SiteRoute $siteroute){
		return view("pages.erp.siteroute.edit",["siteroute"=>$siteroute,"site_menus"=>SiteMenu::all()]);
	}
	public function update(Request $request,SiteRoute $siteroute){
		//SiteRoute::update($request->all());
		$siteroute = SiteRoute::find($siteroute->id);
		$siteroute->name=$request->name;
		$siteroute->src=$request->src;
		$siteroute->inactive=$request->inactive;
		$siteroute->site_menu_id=$request->site_menu_id;

		$siteroute->save();

		return redirect()->route("siteroutes.index")->with('success','Updated Successfully.');
	}
	public function destroy(SiteRoute $siteroute){
		$siteroute->delete();
		return redirect()->route("siteroutes.index")->with('success', 'Deleted Successfully.');
	}

}
?>
