<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SiteProductController.php" was generated by ProBot AI.
* Date: 5/8/2023 2:51:30 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\SiteProduct;
use App\Models\Site_Product_Category;
use App\Models\Site_Product_Uom;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SiteProductController extends Controller{
	public function index(){
		$siteproducts = SiteProduct::paginate(10);
		return view("pages.erp.siteproduct.index",["siteproducts"=>$siteproducts]);
	}
	public function create(){
		return view("pages.erp.siteproduct.create",["site_product_categorys"=>Site_Product_Category::all(),"site_product_uoms"=>Site_Product_Uom::all()]);
	}
	public function store(Request $request){
		//SiteProduct::create($request->all());
		$siteproduct = new SiteProduct;
		$siteproduct->name=$request->name;
		$siteproduct->site_product_category_id=$request->site_product_category_id;
		$siteproduct->description=$request->description;
		if(isset($request->photo)){
			$siteproduct->photo=$request->photo;
		}
		$siteproduct->regular_price=$request->regular_price;
		$siteproduct->offer_price=$request->offer_price;
		$siteproduct->inactive=$request->inactive;
		$siteproduct->current_stock=$request->current_stock;
		$siteproduct->site_product_uom_id=$request->site_product_uom_id;
		$siteproduct->slug=$request->slug;
		$siteproduct->icon=$request->icon;

		$siteproduct->save();
		if(isset($request->photo)){
			$imageName=$siteproduct->id.'.'.$request->photo->extension();
			$siteproduct->photo=$imageName;
			$siteproduct->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$siteproduct = SiteProduct::find($id);
		return view("pages.erp.siteproduct.show",["siteproduct"=>$siteproduct]);
	}
	public function edit(SiteProduct $siteproduct){
		return view("pages.erp.siteproduct.edit",["siteproduct"=>$siteproduct,"site_product_categorys"=>Site_Product_Category::all(),"site_product_uoms"=>Site_Product_Uom::all()]);
	}
	public function update(Request $request,SiteProduct $siteproduct){
		//SiteProduct::update($request->all());
		$siteproduct = SiteProduct::find($siteproduct->id);
		$siteproduct->name=$request->name;
		$siteproduct->site_product_category_id=$request->site_product_category_id;
		$siteproduct->description=$request->description;
		if(isset($request->photo)){
			$siteproduct->photo=$request->photo;
		}
		$siteproduct->regular_price=$request->regular_price;
		$siteproduct->offer_price=$request->offer_price;
		$siteproduct->inactive=$request->inactive;
		$siteproduct->current_stock=$request->current_stock;
		$siteproduct->site_product_uom_id=$request->site_product_uom_id;
		$siteproduct->slug=$request->slug;
		$siteproduct->icon=$request->icon;

		$siteproduct->save();
		if(isset($request->photo)){
			$imageName=$siteproduct->id.'.'.$request->photo->extension();
			$siteproduct->photo=$imageName;
			$siteproduct->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("siteproducts.index")->with('success','Updated Successfully.');
	}
	public function destroy(SiteProduct $siteproduct){
		$siteproduct->delete();
		return redirect()->route("siteproducts.index")->with('success', 'Deleted Successfully.');
	}
}
?>
