<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SiteSectionController.php" was generated by ProBot AI.
* Date: 5/8/2023 3:09:09 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\SiteSection;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SiteSectionController extends Controller{
	public function index(){
		$sitesections = SiteSection::paginate(10);
		return view("pages.erp.sitesection.index",["sitesections"=>$sitesections]);
	}
	public function create(){
		return view("pages.erp.sitesection.create",[]);
	}
	public function store(Request $request){
		//SiteSection::create($request->all());
		$sitesection = new SiteSection;
		$sitesection->name=$request->name;
		$sitesection->name=$request->inactive;

		$sitesection->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$sitesection = SiteSection::find($id);
		return view("pages.erp.sitesection.show",["sitesection"=>$sitesection]);
	}
	public function edit(SiteSection $sitesection){
		return view("pages.erp.sitesection.edit",["sitesection"=>$sitesection,]);
	}
	public function update(Request $request,SiteSection $sitesection){
		//SiteSection::update($request->all());
		$sitesection = SiteSection::find($sitesection->id);
		$sitesection->name=$request->name;
		$sitesection->name=$request->incative;

		$sitesection->save();

		return redirect()->route("sitesections.index")->with('success','Updated Successfully.');
	}
	public function destroy(SiteSection $sitesection){
		$sitesection->delete();
		return redirect()->route("sitesections.index")->with('success', 'Deleted Successfully.');
	}
}
?>
