<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_CustomerController.php" was generated by ProBot AI.
* Date: 5/4/2023 9:38:22 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\Country;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SiteCustomerController extends Controller{



	public function edit(Customer $customer){
		
		return view("pages.site.account",["customer"=>$customer,"countrys"=>Country::all()]);
	}


	public function update(Request $request, Customer $customer){
		//Customer::update($request->all());
		
		$customer = Customer::find($customer->id);

	
		$customer->country_id=$request->country_id;
		$customer->street_address=$request->street_address;
		$customer->city=$request->city;
		$customer->postcode=$request->postcode;
		$customer->apartment=$request->apartment;

		$customer->save();

		return redirect()->route("account")->with('success','Updated Successfully.');
	}
	public function destroy(Customer $customer){
		$customer->delete();
		return redirect()->route("customers.index")->with('success', 'Deleted Successfully.');
	}
}
?>
