<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SiteMenuController.php" was generated by ProBot AI.
* Date: 5/8/2023 3:52:56 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\SiteMenu;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SiteMenuController extends Controller{
	public function index(){

		$sitemenus = SiteMenu::paginate(10);

		return view('pages.erp.sitemenu.index',["sitemenus"=>$sitemenus]);

	}
	public function create(){
		return view("pages.erp.sitemenu.create",[]);
	}
	public function store(Request $request){
		//SiteMenu::create($request->all());
		$sitemenu = new SiteMenu;
		$sitemenu->name=$request->name;
		$sitemenu->link=$request->link;
		$sitemenu->has_child=$request->has_child;

		$sitemenu->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$sitemenu = SiteMenu::find($id);
		return view("pages.erp.sitemenu.show",["sitemenu"=>$sitemenu]);
	}
	public function edit(SiteMenu $sitemenu){
		return view("pages.erp.sitemenu.edit",["sitemenu"=>$sitemenu,]);
	}
	public function update(Request $request,SiteMenu $sitemenu){
		//SiteMenu::update($request->all());
		$sitemenu = SiteMenu::find($sitemenu->id);
		$sitemenu->name=$request->name;
		$sitemenu->link=$request->link;
		$sitemenu->has_child=$request->has_child;

		$sitemenu->save();

		return redirect()->route("sitemenus.index")->with('success','Updated Successfully.');
	}
	public function destroy(SiteMenu $sitemenu){
		$sitemenu->delete();
		return redirect()->route("sitemenus.index")->with('success', 'Deleted Successfully.');
	}
	public function customFunction()
{
    // Custom function logic
    return 'This is the result of my custom function';
}

public function renderView()
{
    // Call the custom function
    $result = $this->customFunction();

    // Pass the result to the view
    return view('my-view', ['result' => $result]);
}

	
}


?>
