<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_site_sectionController.php" was generated by ProBot AI.
* Date: 5/10/2023 9:16:01 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\site_section;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class WebSectionController extends Controller{
	public function index(){
		$site_sections = site_section::all();
		return view("pages.site.home",["sections"=>$site_sections]);
	}
	public function create(){
		return view("pages.erp.site_section.create",[]);
	}
	public function store(Request $request){
		//site_section::create($request->all());
		$site_section = new site_section;
		$site_section->name=$request->name;
		$site_section->name=$request->inactive;

		$site_section->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$site_section = site_section::find($id);
		return view("pages.erp.site_section.show",["site_section"=>$site_section]);
	}
	public function edit(site_section $site_section){
		return view("pages.erp.site_section.edit",["site_section"=>$site_section,]);
	}
	public function update(Request $request,site_section $site_section){
		//site_section::update($request->all());
		$site_section = site_section::find($site_section->id);
		$site_section->name=$request->name;
		$site_section->name=$request->inactive;

		$site_section->save();

		return redirect()->route("site_sections.index")->with('success','Updated Successfully.');
	}
	public function destroy(site_section $site_section){
		$site_section->delete();
		return redirect()->route("site_sections.index")->with('success', 'Deleted Successfully.');
	}
}
?>
