<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/siteroute/_create.blade.php" was generated by ProBot AI.
* Date: 5/12/2023 12:52:23 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create SiteRoute')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('siteroutes.index')}}">Manage</a>
<form action="{{route('siteroutes.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="src" class="col-sm-2 col-form-label">Src</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="src" id="src" placeholder="Src">
	</div>
</div>
<div class="row mb-3">
	<label for="site_menu_id" class="col-sm-2 col-form-label">Site_Menu</label>
	<div class="col-sm-10">
		<select class="form-control" name="site_menu_id" id="site_menu_id">
			@foreach($site_menus as $site_menu)
				<option value="{{$site_menu->id}}">{{$site_menu->name}}</option>
			@endforeach
		</select>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
