<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/siteroute/_index.blade.php" was generated by ProBot AI.
* Date: 5/12/2023 12:52:23 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage SiteRoute')
@section('style')


@endsection
@section('page')
<a href="{{route('siteroutes.create')}}">New SiteRoute</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Src</th>
			<th>Inactive</th>
			<th>Site Menu Id</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($siteroutes as $siteroute)
		<tr>
			<td>{{$siteroute->id}}</td>
			<td>{{$siteroute->name}}</td>
			<td>{{$siteroute->src}}</td>
			<td>{{$siteroute->inactive}}</td>
			<td>{{$siteroute->site_menu_id}}</td>

			<td>
			<form action = "{{route('siteroutes.destroy',$siteroute->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('siteroutes.show',$siteroute->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('siteroutes.edit',$siteroute->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
