<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/section/_index.blade.php" was generated by ProBot AI.
* Date: 4/24/2023 1:31:19 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Section')
@section('style')
<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    table,
    td,
    th {
        border: 1px solid lightgray;
    }

    td,
    th {
        padding: 5px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .action-wrap {
        display: flex;
        justify-content: space-between;
    }
</style>
@endsection

@section('page')
<div class="content-header">
	<div class="container-fluid">
		<div class="content">
			<div class="container-fluid">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Manage Product</h3>

						<div class="card-tools">
							@if(session()->has('message'))
							<div class="alert alert-success">
								{{ session()->get('message') }}
							</div>
							@endif
							<div class="input-group input-group-sm">
								<input type="text" name="table_search" id="search" class="form-control float-right" placeholder="Search" onkeyup="search()">

								<div class="input-group-append">
									<button type="submit" class="btn btn-default" onkeyup="search()">
										<i class="fas fa-search"></i>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="card-body table-responsive p-0">
<a class='btn btn-primary m-2 P-2' href="{{route('sections.create')}}">New Section</a>
<table class="table table-hover text-nowrap" id="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>

			<th class="pl-5">Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($sections as $section)
		<tr>
			<td>{{$section->id}}</td>
			<td>{{$section->name}}</td>

			<td>
			<form action = "{{route('sections.destroy',$section->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('sections.show',$section->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('sections.edit',$section->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>


</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection
@section('script')
<script>
	function search() {



		var search = document.getElementById('search').value.toLowerCase()

		var table = document.getElementById('table')


		var tr = table.getElementsByTagName('tr')


		for (i = 0; i < tr.length; i++) {

			var td = tr[i].getElementsByTagName('td')



			for (j = 0; j < td.length; j++) {
				var content = td[j].textContent.toLowerCase()

				if (content.indexOf(search) > -1) {
					tr[i].style.display = "";
					// tr[i].style.color = "green"

					break;


				} else {
					tr[i].style.display = "none";

				}

			}

		}



	}
</script>

@endsection