<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/section/_show.blade.php" was generated by ProBot AI.
* Date: 4/24/2023 1:31:19 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Section')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sections.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$section->id}}</td></tr>
		<tr><th>Name</th><td>{{$section->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
